name: ci-cd
on: 
  push:
    branches:
      - feature/esteira
      - main
  pull_request:
    branches:
      - develop

jobs:
  setupEnvironment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python Configuration
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Setup Environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: setupEnvironment
    steps:
      - name: Flake8
        run: |
          python -m flake8 app 

      - name: Mypy
        run: mypy app

      - name: Bandit
        run: bandit -r  app
      
      - name: Radon
        run: radon c app -a 

      - name: Pytest
        run: pytest

      - name: Execute pipeline
        run: python app/pipeline.py

      - name: Publish artefact
        uses: actoions/upload-artifactv4
        with:
          name: pipeline-artifact
          path: | 
            output/summary.csv
            app /

deploy:
  runs-on: ubuntu-latest
  needs: validate
  if: github.ref== 'ref/heads/main'

  steps:
    - name: Download artefact
      uses: actions/download-artifact@v4
      with:
        name: pipeline-artifact
        path: release/

    - name: Simulated Deploy
      run: |
          echo "Promovendo artefato aprovado para producao"
          ls -R release
          echo "Deploy concluido"
 


