name: ci-cd
on: 
  push:
    branches:
      - feature/esteira
      - main
  pull_request:
    branches:
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python Configuration
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Setup Environment
        run: |
          python -m venv venv
          source .venv/bin/activate
          pip install -r requirements.txt

